/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicsPackegeName;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    /**
     * java fundemental
     * @param args
     */
    public static void main(String[] args) {
/**
 * pularaize
 */
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");
        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");
        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
        /**
         * FlipHeads()
         */
        flipNHeads(10);
        /**
         * clock()
         */
        clock();
    }

    /**
     *
     * @param word to check it if need to add to it apostrophe s
     * @param num to add to the word
     * @return the word with a postrophe s or not
     */
    public static String pluralize(String word , int num ){
        if(num != 1 ){
            return word+'s'  ;
        }
        else {
            return  word ;
        }
    }

    /**
     *
     * @param n : number of flips
     */
    public static void flipNHeads(int n) {
        int headCount = 0;
        int headsMax = 0;
        int[] arr = {};
        for (int i = 0; i < n; i++) {
            if (Math.random() < 0.5) {
                System.out.println("tails");
                if (headCount > headsMax) {
                    headsMax = headCount;
                    headCount = 0;
                }
            } else {
                System.out.println("heads");
                headCount++;
            }
        }
        System.out.println("It took " + n + " flips to flip " + Math.max(headCount, headsMax) + " head in a row.");
    }

    /**
     * follow the time
     */
    public static void clock() {
        int currentSec = 0;
        for (int i = 0; i >= 0; i++) {
            LocalDateTime now = LocalDateTime.now();
            int second = now.getSecond();
            if (currentSec != second) {
                currentSec=second;
                String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

                System.out.println(time);
            }

        }


    }


}
