/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrarySourcePackege;
import org.junit.Test;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    Library classUnderTest = new Library();
    @Test public void testSomeLibraryMethod() {

        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    @DisplayName("contains duplicated locates")
    public void testContainsDuplicatesFalse() {
        int[] arr = {3, 2, 1, 5};
        assertEquals("contains duplicated locates", false,
                classUnderTest.containsDuplicates(arr));
    }

    @RepeatedTest(5)
    @DisplayName("contains duplicated locates")
    public void testContainsDuplicatesTrue() {
        int[] arr = {3, 2, 1, 5, 0, -1, 9, 3, 1};
        assertEquals("contains duplicated locates", true,
                classUnderTest.containsDuplicates(arr));
    }

    @RepeatedTest(5)
    @DisplayName("Calculating Averages")
    public void testCalculatingAverages() {
        int[] arr1 = {3, 2, 1, 5};
        int[] arr2 = {20, 27, 30, 50};
        Assertions.assertEquals(2.7,
                classUnderTest.calcAverage(arr1), "Calculating Averages");
        Assertions.assertEquals(31.7,
                classUnderTest.calcAverage(arr2), "Calculating Averages");
    }

    @RepeatedTest(5)
    @DisplayName("2D Array")
    public void testArraysOfArrays() {
        int[][] testWeeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}};
        int [] arrTest = {66, 64, 58, 65, 71, 57, 60};

        Assertions.assertEquals(arrTest,
                classUnderTest.lowestAvg2DArr(testWeeklyMonthTemperatures),
                "Arrays Of Arrays");
    }
}
