/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Review_packege;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test public void testToStringResturant(){
        Resturant resturant = new Resturant("good","judy",5);
        assertEquals("the Restaurant "+resturant.getName() + " has " +resturant.getNoOfStars() +"  stars  " + resturant.getPriceCategory() +" $",resturant.tostring());
    }
    @Test public void testToStringReview(){
        Review review = new Review("good","judy",5);
        assertEquals(" the Restaurant "+review.getAuthor()+ "  voted " +review.getStars() +"  stars  " + review.getBody(),review.tostring());
    }
@Test public void testAddReview(){
    Review rev1 = new Resturant("judy","good",5);
    Resturant reviewCasting = (Resturant) rev1;
    assertEquals("shawarmaji=[good, judy, 5]",reviewCasting.addReview(rev1));
}


}
