/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Inheritance.com;

import java.util.ArrayList;
import java.util.HashMap;

//import Restaurant;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
//
    public static void main(String[] args) {

        Restaurant res = new Restaurant("Zanjbeel",7,"$$");
        Restaurant rev1 = new Review(" very goood", "Qusai Alamarat",5 );
        Restaurant res1 = new Restaurant("Mecdonalds ",6,"$$$");
        Restaurant rev4 = new Review(" its ok ", "Mahmood Alashqar",5 );
        Review rev2 = (Review) rev1;
        Review rev3 = (Review) rev4;
        res.addReview(rev2);
        res1.addReview(rev3);

    }
}
