/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trainigTesting;

import java.util.ArrayList;
import java.util.HashMap;

public class App {


    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashMap<String,HashMap<String,ArrayList>> all = new HashMap<>();

        System.out.println(new App().getGreeting());
        System.out.println(new App().getGreeting());

        Review rev1 = new Resturant("judy","good","5",all);
//        Review rev2 = new Resturant("qusai","ok","3",all);
        Resturant reviewCasting = (Resturant) rev1;
        reviewCasting.setName("Zanjabeel");
        reviewCasting.addReview(rev1);
//        reviewCasting.addReview(rev2);
        Review rev3 = new Shop("very well","JudyBataineh","4",all);
        Shop castingShop  =(Shop) rev3;
        castingShop.setShopName("Nike");
        castingShop.addReview(rev3);
        Review rev4= new Theater("wonderful","JOJO","4","Plan Escape",all);
        Theater castingTheater = (Theater) rev4;
        castingTheater.addReview(rev4);
//        Theater movie = new Theater();
        castingTheater.addMovie("Casino Royal",true);
        castingTheater.addMovie("Heat",false);
        castingTheater.whichMovieOnSecreen();
//        castingTheater.removeMovie("ss");
        castingTheater.output();
        System.out.println(castingTheater.allMovie);
        System.out.println(all);

    }
}
